### ISSUE TITLE
Can I implement this patch in Intel UHD 630 gen 10 

### ISSUE THREAD

**Issue by efrizalnf** [perez987/Intel-UHD-Graphics-630-on-macOS#4]
Hii, Can I implement this patch in Intel UHD 630 gen 10 (Core i5 10400)?

**Comment by perez987** [comment]
@efrizalnf 
I think so, you can try, used `AAPL,ig-platform-id` are the same as 9th gen.
I suppose that you have a AMD dGPU, is it so? Then, get the headless mode code.

**Comment by efrizalnf** [comment]
my dGPU is GT730 Kepler can I to do that?

**Comment by perez987** [comment]
@efrizalnf 
Try and comment, if the GT 730 works fine you must be able to have the iGPU as headless mode.

**Comment by efrizalnf** [comment]
Ok, will try.
